backend:
  name: git-gateway
  branch: +tailwind  # Użyj swojej głównej gałęzi

collections:
  - name: "posts"  # Nazwa kolekcji
    label: "Blog Posts"  # Etykieta kolekcji
    folder: "src/pages/posts"  # Folder z postami Markdown
    create: true  # Umożliwia tworzenie nowych postów
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"  # Format slug
    fields:
      - { label: "Title", name: "title", widget: "string" }  # Tytuł posta
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }  # Data publikacji
      - { label: "Description", name: "description", widget: "text" }  # Opis posta
      - { label: "Author", name: "author", widget: "string" }  # Autor posta
      - { label: "Image URL", name: "image.url", widget: "image" }  # URL obrazu
      - { label: "Image Alt Text", name: "image.alt", widget: "string" }  # Tekst alternatywny dla obrazu
      - { label: "Tags", name: "tags", widget: "list", field: { widget: "string" } }  # Tagowanie posta
